Core/Areas/Overham/Models/Band/SearchResultsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Areas.Overham.Models.Band
{
    public class SearchResultsViewModel
    {
        public int[] BandId { get; set; }
    }
}

Core/Areas/Overham/Models/Band/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Areas.Overham.Models.Band
{
    public class SearchViewModel
    {
        public string FrequencyInHz { get; set; }
    }
}

Core/Areas/Overham/Models/Callsign/InfoResultsViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Core.Areas.Overham.Models.Callsign
{
    public class InfoResultsViewModel
    {
        public string Region { get; set; }
        public string Country { get; set; }
        public string Callsign { get; set; }
        public string Type { get; set; }
        public string AmateurClass { get; set; }
    }
}

Core/Areas/Overham/Models/Callsign/InfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Areas.Overham.Models.Callsign
{
    public class InfoViewModel
    {
        public string Callsign { get; set; }
    }
}

Core/Areas/Overham/Models/Recordings/InfoResultsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Areas.Overham.Models.Recordings
{
    public class InfoResultsViewModel
    {
        public string Mode { get; set; }
        public DateTime WhenStart { get; set; }
        public int Length { get; set; }
        public string Callsign { get; set; }
        public int HZFreq { get; set; }
        public string Model { get; set; }
        public int Band { get; set; }
        public string Maidenhead { get; set; }
        public string Direction { get; set; }
    }
}

Core/Areas/Overham/Models/Recordings/InfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Areas.Overham.Models.Recordings
{
    public class InfoViewModel
    {
        public string Id { get; set; }
    }
}

Core/Areas/Overham/Models/Recordings/ResultsModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Areas.Overham.Models.Recordings
{
    public class ResultsModel
    {
        public string Duration { get; set; }
        public string HZFreq { get; set; }
        public string Id { get; set; }
        public DateTime WhenStart { get; set; }
    }
}

Core/Areas/Overham/Models/Recordings/SearchResultsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Areas.Overham.Models.Recordings
{
    public class SearchResultsViewModel
    {
        public int ResultCount { get; set; }
        public List<ResultsModel> Results { get; set; }
        public string EndpointCurrentVersionUrl { get; set; }
    }
}

Core/Areas/Overham/Models/Recordings/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Areas.Overham.Models.Recordings
{
    public class SearchViewModel
    {
        public string StartHZ { get; set; }
        public string EndHZ { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
    }
}

Core/Areas/Overham/Models/Recordings/StatsResultsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Areas.Overham.Models.Recordings
{
    public class StatsResultsViewModel
    {
        public string UploadedCount { get; set; }
        public DateTime LastDump { get; set; }
        public string Available { get; set; }
        public string TotalCount { get; set; }
        public DateTime Earliest { get; set; }
        public DateTime Latest { get; set; }
        public string ModeAmCount { get; set; }
        public string ModeFmCount { get; set; }
        public string ModeLsbCount { get; set; }
        public string ModeUsbCount { get; set; }
        public string ModeDVCount { get; set; }
        public string ModeCWCount { get; set; }
    }
}

Core/Areas/Overham/Controllers/RecordingsController.cs
using Core.Areas.Overham.Models;
using Core.Areas.Overham.Models.Recordings;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Overham.Client;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Core.Areas.Overham.Controllers
{
    [Area("Overham")]
    public class RecordingsController : Controller
    {
        private readonly AppSettings _appSettings;

        public RecordingsController(IOptions<AppSettings> appSettings)
        {
            _appSettings = appSettings.Value;
        }

        public async Task<IActionResult> StatsResults()
        {
            try
            {
                OverhamClient overhamClient = new OverhamClient(_appSettings.EndpointCurrentVersionUrl());
                global::Overham.Client.Models.Recordings.Stats.ResponseModel responseModel = await overhamClient.GetRecordingStatsAsync();
                StatsResultsViewModel statsResultsViewModel = new StatsResultsViewModel();
                statsResultsViewModel.Available = responseModel.Data.Available;
                statsResultsViewModel.Earliest = responseModel.Data.Earliest;
                statsResultsViewModel.LastDump = responseModel.Data.LastDump;
                statsResultsViewModel.Latest = responseModel.Data.Latest;
                statsResultsViewModel.ModeAmCount = responseModel.Data.ModeAmCount;
                statsResultsViewModel.ModeCWCount = responseModel.Data.ModeCWCount;
                statsResultsViewModel.ModeDVCount = responseModel.Data.ModeDVCount;
                statsResultsViewModel.ModeFmCount = responseModel.Data.ModeFmCount;
                statsResultsViewModel.ModeLsbCount = responseModel.Data.ModeLsbCount;
                statsResultsViewModel.ModeUsbCount = responseModel.Data.ModeUsbCount;
                statsResultsViewModel.TotalCount = responseModel.Data.TotalCount;
                statsResultsViewModel.UploadedCount = responseModel.Data.UploadedCount;
                return View(statsResultsViewModel);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public IActionResult Info()
        {
            InfoViewModel infoViewModel = new InfoViewModel();
            return View(infoViewModel);
        }

        public async Task<IActionResult> InfoResults(InfoViewModel infoViewModel)
        {
            try
            {
                OverhamClient overhamClient = new OverhamClient(_appSettings.EndpointCurrentVersionUrl());
                global::Overham.Client.Models.Recordings.Info.ResponseModel responseModel = await overhamClient.GetRecordingInfoAsync(infoViewModel.Id);
                InfoResultsViewModel infoResultsModel = new InfoResultsViewModel();
                infoResultsModel.Band = responseModel.Data.Band;
                infoResultsModel.Callsign = responseModel.Data.Callsign;
                infoResultsModel.Direction = responseModel.Data.Direction;
                infoResultsModel.HZFreq = responseModel.Data.HZFreq;
                infoResultsModel.Length = responseModel.Data.Length;
                infoResultsModel.Maidenhead = responseModel.Data.Maidenhead;
                infoResultsModel.Mode = responseModel.Data.Mode;
                infoResultsModel.Model = responseModel.Data.Model;
                infoResultsModel.WhenStart = responseModel.Data.WhenStart;
                return View(infoResultsModel);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }

        public IActionResult Search()
        {
            SearchViewModel searchViewModel = new SearchViewModel();
            searchViewModel.StartTime = DateTime.Today;
            searchViewModel.EndTime = DateTime.Today;
            searchViewModel.StartHZ = "430825000";
            searchViewModel.EndHZ = "430850000";
            return View(searchViewModel);
        }

        public async Task<IActionResult> SearchResults(SearchViewModel searchViewModel)
        {
            try
            {
                OverhamClient overhamClient = new OverhamClient(_appSettings.EndpointCurrentVersionUrl());
                global::Overham.Client.Models.Recordings.Search.ResponseModel responseModel = await overhamClient.GetRecordingsByRangeAsync(
                    searchViewModel.StartHZ,
                    searchViewModel.EndHZ, 
                    ((DateTimeOffset)searchViewModel.StartTime).ToUnixTimeSeconds().ToString(), 
                    ((DateTimeOffset)searchViewModel.EndTime).ToUnixTimeSeconds().ToString());

                SearchResultsViewModel searchResultsViewModel = new SearchResultsViewModel();
                searchResultsViewModel.ResultCount = responseModel.Data.ResultCount;
                // Just to avoid using AutoMapper, use some crazy Linq.
                searchResultsViewModel.Results = responseModel.Data.Results.Select(m => new ResultsModel() { Duration = m.Duration, HZFreq = m.HZFreq, Id = m.Id, WhenStart = m.WhenStart }).ToList();
                searchResultsViewModel.EndpointCurrentVersionUrl = _appSettings.EndpointCurrentVersionUrl();
                return View(searchResultsViewModel);
            }
            catch (Exception ex)
            {
                return View("Error");
            }
        }
    }
}

Core/Areas/Overham/Views/Recordings/Info.cshtml
@model Core.Areas.Overham.Models.Recordings.InfoViewModel

<h2>Overham</h2>

<h4>Recordings info</h4>

@using (Html.BeginForm("InfoResults", "Recordings", FormMethod.Post))
{
    @Html.LabelFor(m => m.Id)
    @Html.TextBoxFor(m => m.Id)
    @Html.ValidationMessageFor(m => m.Id)
    <input type="submit" value="Submit" />
}

Core/Areas/Overham/Views/Recordings/InfoResults.cshtml
@model Core.Areas.Overham.Models.Recordings.InfoResultsViewModel

<h2>Overham</h2>

<h4>Recordings info results</h4>

@Html.LabelFor(m => m.Band)
@Html.DisplayFor(m => m.Band)
<br />
@Html.LabelFor(m => m.Callsign)
@Html.DisplayFor(m => m.Callsign)
<br />
@Html.LabelFor(m => m.Direction)
@Html.DisplayFor(m => m.Direction)
<br />
@Html.LabelFor(m => m.HZFreq)
@Html.DisplayFor(m => m.HZFreq)
<br />
@Html.LabelFor(m => m.Length)
@Html.DisplayFor(m => m.Length)
<br />
@Html.LabelFor(m => m.Maidenhead)
@Html.DisplayFor(m => m.Maidenhead)
<br />
@Html.LabelFor(m => m.Mode)
@Html.DisplayFor(m => m.Mode)
<br />
@Html.LabelFor(m => m.Model)
@Html.DisplayFor(m => m.Model)
<br />
@Html.LabelFor(m => m.WhenStart)
@Html.DisplayFor(m => m.WhenStart)

Core/Areas/Overham/Views/Recordings/Search.cshtml
@model Core.Areas.Overham.Models.Recordings.SearchViewModel

<h2>Overham</h2>

<h4>Recordings search</h4>

@using (Html.BeginForm("SearchResults", "Recordings", FormMethod.Post))
{
    @Html.LabelFor(m => m.StartTime)
    @Html.TextBoxFor(m => m.StartTime, new { @type = "date" })
    @Html.ValidationMessageFor(m => m.StartTime)
    <br />
    @Html.LabelFor(m => m.EndTime)
    @Html.TextBoxFor(m => m.EndTime, new { @type = "date" })
    @Html.ValidationMessageFor(m => m.EndTime)
    <br />
    @Html.LabelFor(m => m.StartHZ)
    @Html.TextBoxFor(m => m.StartHZ)
    @Html.ValidationMessageFor(m => m.StartHZ)
    <br />
    @Html.LabelFor(m => m.EndHZ)
    @Html.TextBoxFor(m => m.EndHZ)
    @Html.ValidationMessageFor(m => m.EndHZ)
    <br />
    <input type="submit" value="Submit" />
}

Core/Areas/Overham/Views/Recordings/SearchResults.cshtml
@model Core.Areas.Overham.Models.Recordings.SearchResultsViewModel

<h2>Overham</h2>

<h4>Recordings search results</h4>

@Html.LabelFor(m => m.ResultCount)
@Html.DisplayFor(m => m.ResultCount)
<br />

@if (Model.Results.Count > 1)
{
<table border="1">
    <tr>
        <th>Duration</th>
        <th>HZFreq</th>
        <th>Id</th>
        <th>WhenStart</th>
        <th>Download</th>
    </tr>
    @foreach (var result in Model.Results)
    {
        <tr>

            <th>@result.Duration</th>
            <th>@result.HZFreq</th>
            <th>@result.Id</th>
            <th>@result.WhenStart</th>
            <th><a href="@Model.EndpointCurrentVersionUrl/recordings/download?id=@result.Id" target="_blank">Download</a></th>

        </tr>
    }
</table>
}
else
{
    <p>No results found.</p>
}

Core/Areas/Overham/Views/Recordings/StatsResults.cshtml
@model Core.Areas.Overham.Models.Recordings.StatsResultsViewModel

<h2>Overham</h2>

<h4>Stats results</h4>

@Html.LabelFor(m => m.Available)
@Html.DisplayFor(m => m.Available)
<br>
@Html.LabelFor(m => m.Earliest)
@Html.DisplayFor(m => m.Earliest)
<br>
@Html.LabelFor(m => m.LastDump)
@Html.DisplayFor(m => m.LastDump)
<br>
@Html.LabelFor(m => m.Latest)
@Html.DisplayFor(m => m.Latest)
<br>
@Html.LabelFor(m => m.ModeAmCount)
@Html.DisplayFor(m => m.ModeAmCount)
<br>
@Html.LabelFor(m => m.ModeCWCount)
@Html.DisplayFor(m => m.ModeCWCount)
<br>
@Html.LabelFor(m => m.ModeDVCount)
@Html.DisplayFor(m => m.ModeDVCount)
<br>
@Html.LabelFor(m => m.ModeFmCount)
@Html.DisplayFor(m => m.ModeFmCount)
<br>
@Html.LabelFor(m => m.ModeLsbCount)
@Html.DisplayFor(m => m.ModeLsbCount)
<br>
@Html.LabelFor(m => m.ModeUsbCount)
@Html.DisplayFor(m => m.ModeUsbCount)
<br>
@Html.LabelFor(m => m.TotalCount)
@Html.DisplayFor(m => m.TotalCount)
<br>
@Html.LabelFor(m => m.UploadedCount)
@Html.DisplayFor(m => m.UploadedCount)